app/src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MessageRepository::class)]
class Message
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $subject = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'messages')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $sender = null;

    #[ORM\ManyToOne(inversedBy: 'rmessages')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $recipient = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $modify_at = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isResponse = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isRead = null;

    /**
     * @var Collection<int, File>
     */
    #[ORM\OneToMany(targetEntity: File::class, mappedBy: 'message')]
    private Collection $files;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $lastSender = null;



    #[ORM\Column(nullable: true)]
    private ?bool $isSenderDelete = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isRecipientDelete = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'favorite')]
    private Collection $favorite;

    public function __construct()
    {
        $this->files = new ArrayCollection();
        $this->favorite = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(?string $subject): static
    {
        $this->subject = $subject;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getSender(): ?User
    {
        return $this->sender;
    }

    public function setSender(?User $sender): static
    {
        $this->sender = $sender;

        return $this;
    }

    public function getRecipient(): ?User
    {
        return $this->recipient;
    }

    public function setRecipient(?User $recipient): static
    {
        $this->recipient = $recipient;

        return $this;
    }

    public function getModifyAt(): ?\DateTimeImmutable
    {
        return $this->modify_at;
    }

    public function setModifyAt(?\DateTimeImmutable $modify_at): static
    {
        $this->modify_at = $modify_at;

        return $this;
    }

    public function isResponse(): ?bool
    {
        return $this->isResponse;
    }

    public function setIsResponse(?bool $isResponse): static
    {
        $this->isResponse = $isResponse;

        return $this;
    }

    public function isRead(): ?bool
    {
        return $this->isRead;
    }

    public function setIsRead(?bool $isRead): static
    {
        $this->isRead = $isRead;

        return $this;
    }

    /**
     * @return Collection<int, File>
     */
    public function getFiles(): Collection
    {
        return $this->files;
    }

    public function addFile(File $file): static
    {
        if (!$this->files->contains($file)) {
            $this->files->add($file);
            $file->setMessage($this);
        }

        return $this;
    }

    public function removeFile(File $file): static
    {
        if ($this->files->removeElement($file)) {
            // set the owning side to null (unless already changed)
            if ($file->getMessage() === $this) {
                $file->setMessage(null);
            }
        }

        return $this;
    }

    public function getLastSender(): ?string
    {
        return $this->lastSender;
    }

    public function setLastSender(?string $lastSender): static
    {
        $this->lastSender = $lastSender;

        return $this;
    }

    // src/Entity/Message.php

    public function isUserAllowed(User $user): bool
    {
        // Par exemple, l’utilisateur est autorisé s’il est l’expéditeur ou le destinataire
        return $this->getSender() === $user || $this->getRecipient() === $user;
    }

    public function isSenderDelete(): ?bool
    {
        return $this->isSenderDelete;
    }

    public function setIsSenderDelete(?bool $isSenderDelete): static
    {
        $this->isSenderDelete = $isSenderDelete;

        return $this;
    }

    public function isRecipientDelete(): ?bool
    {
        return $this->isRecipientDelete;
    }

    public function setIsRecipientDelete(?bool $isRecipientDelete): static
    {
        $this->isRecipientDelete = $isRecipientDelete;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getFavorite(): Collection
    {
        return $this->favorite;
    }

    public function addFavorite(User $favorite): static
    {
        if (!$this->favorite->contains($favorite)) {
            $this->favorite->add($favorite);
        }

        return $this;
    }

    public function removeFavorite(User $favorite): static
    {
        $this->favorite->removeElement($favorite);

        return $this;
    }


}

app/src/Controller/MessageController.php
<?php
// src/Controller/MessageController.php
namespace App\Controller;

use App\Entity\File;
use App\Entity\Message;
use App\Form\AnswerForm;
use App\Form\MessageForm;
use App\Repository\MessageRepository;
use App\Repository\UserRepository;
use App\Service\EmailService;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class MessageController extends AbstractController
{
    // Route pour afficher les messages reçus
    #[Route('/messages/inbox', name: 'messages_inbox')]
    public function inbox(Request $request, MessageRepository $messageRepository, PaginatorInterface $paginator): Response
    {
        $user = $this->getUser();

        // Vérifie que l'utilisateur est connecté et du bon type
        if (!$user instanceof \App\Entity\User) {
            throw $this->createAccessDeniedException('Vous devez être connecté pour voir vos messages.');
        }

        $query = $messageRepository->findInboxMessages($user);
        $messages = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            10 // Limite par page
        );

        return $this->render('message/inbox.html.twig', [
            'messages' => $messages,
        ]);
    }

    // Route pour afficher les messages envoyés
    #[Route('/messages/envoye', name: 'messages_sent')]
    public function sent(Request $request, MessageRepository $messageRepository, PaginatorInterface $paginator): Response
    {
        $user = $this->getUser();
        $query = $messageRepository->findSentMessages($user);
        $messages = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            10 // Limite par page
        );

        return $this->render('message/sent.html.twig', [
            'messages' => $messages,
        ]);
    }

    // Route pour afficher les messages favoris
    #[Route('/messages/favoris', name: 'messages_favorite')]
    public function favorite(Request $request, MessageRepository $messageRepository, PaginatorInterface $paginator): Response
    {
        $user = $this->getUser();
        $query = $messageRepository->getFavoriteMessagesQuery($user);
        $messages = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            10 // Limite par page
        );

        return $this->render('message/favorites.html.twig', [
            'messages' => $messages
        ]);
    }

    // Route pour envoyer un message
    #[Route('/messages/send', name: 'message_send')]
    public function send(EmailService $emailSender, Request $request, EntityManagerInterface $em, UserRepository $userRepository, SluggerInterface $slugger): Response
    {
        $user = $this->getUser();
        $message = new Message();

        // Création du formulaire en fonction du rôle de l'utilisateur
        if (in_array('ROLE_PATIENT', $user->getRoles())) {
            $form = $this->createForm(MessageForm::class, $message);
        } else {
            $form = $this->createForm(MessageForm::class, $message, [
                'pro' => true
            ]);
        }

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Gestion des fichiers joints
            $files = $form->get('files')->getData();
            foreach ($files as $file) {
                if ($file) {
                    $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                    $cleanFilename = strtolower($slugger->slug($originalFilename));
                    $newFilename = $cleanFilename . '-' . uniqid() . '.' . $file->guessExtension();
                    $file->move($this->getParameter('secure_uploads_directory'), $newFilename);
                    $piece = new File();
                    $piece->setname($newFilename);
                    $piece->setOriginalName($cleanFilename);
                    $em->persist($piece);
                    $message->addFile($piece);
                }
            }

            $message->setSender($user);
            $message->setLastSender($user->getName());

            // Définition du destinataire en fonction du rôle
            if ($form->has('patient') && $form->get('patient')->getData()) {
                $message->setRecipient($form->get('patient')->getData());
            } else {
                $message->setRecipient($form->get('employer')->getData());
            }

            $now = new \DateTimeImmutable();
            $formattedDate = $now->format('Y-m-d H:i');
            $isoDate = $now->format('c');
            $message->setCreatedAt($now);

            $content = $form->get('content')->getData();
            $message->setContent('<div class="send"> <p>' . htmlspecialchars($content) . '</p> <time datetime="' . $isoDate . '"> Envoyer le : ' . $formattedDate . '</time></div>');
            $message->setModifyAt($now);
            $message->setIsRead(false);
            $message->setIsSenderDelete(false);
            $message->setIsRecipientDelete(false);

            $em->persist($message);
            $em->flush();

            // Envoi de l'email automatique
            $emailSender->sender(
                'no-reply@molecool.com',
                $message->getRecipient()->getEmail(),
                'Nouveau message reçu sur votre compte',
                'new_message',
                [
                    'recipient' => $message->getRecipient(),
                    'sender' => $user,
                    'message' => $message
                ]
            );

            $this->addFlash('success', 'Message envoyé avec succès.');
            return $this->redirectToRoute('messages_inbox');
        }

        return $this->render('message/send.html.twig', [
            'messageForm' => $form,
        ]);
    }

    // Route pour voir un message et y répondre
    #[Route('/messages/view/{id}/{read}', name: 'message_view', requirements: ['read' => '0|1'])]
    public function view(EmailService $emailService, bool $read, Message $message, Request $request, EntityManagerInterface $em, SluggerInterface $slugger): Response
    {
        $user = $this->getUser();

        // Vérifier que l'utilisateur est soit l'expéditeur soit le destinataire
        $this->denyAccessUnlessGranted('MESSAGE_VIEW', $message);

        $form = $this->createForm(AnswerForm::class, $message, []);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Gestion des fichiers joints
            $files = $form->get('files')->getData();
            foreach ($files as $file) {
                if ($file) {
                    $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                    $cleanFilename = strtolower($slugger->slug($originalFilename));
                    $newFilename = $cleanFilename . '-' . uniqid() . '.' . $file->guessExtension();
                    $file->move($this->getParameter('secure_uploads_directory'), $newFilename);
                    $piece = new File();
                    $piece->setname($newFilename);
                    $piece->setOriginalName($cleanFilename);
                    $em->persist($piece);
                    $message->addFile($piece);
                }
            }

            $now = new \DateTimeImmutable();
            $message->setModifyAt($now);
            $sender = $message->getSender();
            $recipient = $message->getRecipient();
            $previewContent = $message->getContent();
            $formattedDate = $now->format('Y-m-d H:i');
            $isoDate = $now->format('c');
            $message->setIsRead(false);
            $message->setLastSender($user->getName());
            $message->setIsSenderDelete(false);
            $message->setIsRecipientDelete(false);

            if ($sender === $user) {
                $message->setContent('<div class="send"> <p>' . htmlspecialchars($form->get('reponse')->getData()) . '</p> <time datetime="' . $isoDate . '"> Envoyer le : ' . $formattedDate . '</time></div>' . $previewContent);
            }

            if ($recipient === $user) {
                $message->setContent('<div class="receive"> <p>' . htmlspecialchars($form->get('reponse')->getData()) . '</p> <time datetime="' . $isoDate . '"> Envoyer le : ' . $formattedDate . '</time></div>' . $previewContent);
                $message->setIsResponse(true);
            }

            $em->flush();

            // Envoi d'un email de notification
            switch ($message->getLastSender()) {
                case $sender->getName():
                    $emailService->sender(
                        'no-reply@molecool.com',
                        $recipient->getEmail(),
                        'Nouveau message reçu sur votre compte',
                        'new_message',
                        [
                            'recipient' => $message->getRecipient(),
                            'sender' => $user,
                            'message' => $message,
                        ]
                    );
                    break;
                case $recipient->getName():
                    $emailService->sender(
                        'no-reply@molecool.com',
                        $sender->getEmail(),
                        'Nouveau message reçu sur votre compte',
                        'new_message',
                        [
                            'recipient' => $message->getRecipient(),
                            'sender' => $user,

app/templates/message/favorites.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messages favoris{% endblock %}
{% block javascripts %}
    <script src="{{ asset('js/message_favoris.js') }}" defer></script>
{% endblock %}

{% block body %}
    <main id="message_favorite" aria-label="Messages favoris">
        <h1 class="hero">Messages favoris</h1>
        <nav class="inbox-nav" aria-label="Navigation des messages">
            <ul>
                <li><a href="{{ path('messages_inbox') }}" aria-label="Aller à la boîte de réception">📥 Boite de recéption</a></li>
                <li><a href="{{ path('message_send') }}" aria-label="Envoyer un nouveau message">✉️ Nouveau message</a></li>
                <li><a href="{{ path('messages_sent') }}" aria-label="Voir les messages envoyés">📤 Messages envoyés</a></li>
            </ul>
        </nav>
        <section class="message-list" role="region" aria-live="polite" aria-atomic="true">
            <ul>
                {% for message in messages %}
                    <li class="message-item {{ message.isRead ? 'read' : 'unread' }}" data-message-id="{{ message.id }}">
                        <a href="{{ path('message_view', { 'id': message.id , 'read': 0 }) }}" aria-label="Voir le message">
                            <p>De : {{ message.lastsender }}</p>
                            <p>{{ message.subject ?: 'Sans sujet' }}</p>
                            <small>Dernier message : {{ message.modifyAt|date('d/m/Y à H:i') }}</small>
                        </a>
                        <button class="favorite-toggle" aria-label="Basculer le favori">
                            {{ app.user.favorite.contains(message) ? '❤️' : '🤍' }}
                        </button>
                    </li>
                {% else %}
                    <li aria-live="polite">Aucun message favori trouvé.</li>
                {% endfor %}
            </ul>
        </section>
        <div class="pagination" aria-label="Pagination des messages">
            {{ knp_pagination_render(messages) }}
        </div>
    </main>
{% endblock %}

app/templates/message/inbox.html.twig
{% extends 'base.html.twig' %}

{% block title %}Boîte de réception !{% endblock %}
{% block javascripts %}
    <script src="{{ asset('js/message_inbox.js') }}" defer></script>
{% endblock %}
{% block body %}
    <main id="message_inbox" aria-label="Boîte de réception des messages">
        <h1 class="hero">Boîte de réception</h1>

        <nav class="inbox-nav" aria-label="Navigation de la boîte de réception">
            <ul>
                <li><a href="{{ path('messages_sent') }}" aria-label="Voir les messages envoyés">📤 Messages envoyés</a></li>
                <li><a href="{{ path('message_send') }}" aria-label="Envoyer un nouveau message">✉️ Nouveau message</a></li>
                <li><a href="{{ path('messages_favorite') }}" aria-label="Voir les messages favoris">❤️ Messages favoris</a></li>
            </ul>
        </nav>

        <section class="message-list" aria-live="polite" aria-atomic="true" role="region">
            {% for label, messages in app.flashes %}
                {% for message in messages %}
                    <div class="alert alert-{{ label }}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endfor %}
            <ul>
                {% for message in messages %}
                    <li class="message-item {{ message.isRead ? 'read' : 'unread' }}" data-message-id="{{ message.id }}">
                        <a href="{{ path('message_view', { 'id': message.id , 'read': 1 }) }}" aria-label="Voir le message de {{ message.lastsender }}">
                            <p>De : {{ message.lastsender }}</p>
                            <p>Objet : {{ message.subject ?: 'Sans sujet' }}</p>
                            <small>Dernier message : {{ message.modifyAt|date('d/m/Y à H:i') }}</small>
                        </a>
                        <div class="message-meta">
                            <p class="status" aria-label="{{ message.isRead ? 'Message lu' : 'Message non lu' }}">
                                {{ message.isRead ? '📖 Lu' : '📩 Non lu' }}
                            </p>
                            <div>
                                <button class="favorite-toggle" aria-label="Basculer le favori">
                                    {{ app.user.favorite.contains(message) ? '❤️' : '🤍' }}
                                </button>
                                <button
                                        class="delete-button"
                                        data-id="{{ message.id }}"
                                        data-csrf="{{ csrf_token('delete' ~ message.id) }}"
                                        aria-label="Supprimer le message">
                                    🗑️
                                </button>
                            </div>
                        </div>
                    </li>
                {% else %}
                    <li class="no-message" aria-live="polite">Aucune conversation.</li>
                {% endfor %}
            </ul>
        </section>
        <div class="pagination" aria-label="Pagination des messages">
            {{ knp_pagination_render(messages) }}
        </div>
    </main>
{% endblock %}

app/templates/message/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MessageController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>/var/www/html/src/Controller/MessageController.php</code></li>
        <li>Your template at <code>/var/www/html/templates/message/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

app/templates/message/send.html.twig
{% extends 'base.html.twig' %}

{% block title %}Envoyer un message{% endblock %}

{% block body %}
    <main class="form" aria-label="Formulaire d'envoi de message">
        <h1>Envoyer un message</h1>

        {{ form_start(messageForm) }}

        {% if messageForm.patient is defined %}
            {{ form_row(messageForm.patient) }}
        {% endif %}

        {% if messageForm.employer is defined %}
            {{ form_row(messageForm.employer) }}
        {% endif %}

        {{ form_row(messageForm.subject) }}
        {{ form_row(messageForm.content) }}
        {{ form_row(messageForm.files) }}

        <button type="submit" aria-label="Envoyer le message">Envoyer</button>

        {{ form_end(messageForm) }}

    </main>
{% endblock %}

app/templates/message/sent.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MessageController!{% endblock %}
{% block javascripts %}
    <script src="{{ asset('js/message_inbox.js') }}" defer></script>
{% endblock %}

{% block body %}
    <main id="message_sent" aria-label="Messages envoyés">
        <h1 class="hero">Messages envoyés</h1>

        <nav class="inbox-nav" aria-label="Navigation des messages">
            <ul>
                <li><a href="{{ path('messages_inbox') }}" aria-label="Aller à la boîte de réception">📥 Boite de recéption</a></li>
                <li><a href="{{ path('message_send') }}" aria-label="Envoyer un nouveau message">✉️ Nouveau message</a></li>
                <li><a href="{{ path('messages_favorite') }}" aria-label="Voir les messages favoris">❤️ Messages favoris</a></li>
            </ul>
        </nav>
        <section class="message-list" role="region" aria-live="polite" aria-atomic="true">
            <ul>
                {% for message in messages %}
                    <li class="message-item"  data-message-id="{{ message.id }}">
                        <a href="{{ path('message_view', {
                            'id': message.id,
                            'read': 0
                        }) }}" aria-label="Voir le message">
                            <p>À : {% if message.sender.name == message.lastsender %}
                                    {{ message.recipient.name }}
                                {% elseif message.recipient.name == message.lastsender %}
                                    {{ message.sender.name }}
                                {% endif %}
                            </p>
                            <p>{{ message.subject ?: 'Sans sujet' }}</p>
                            <small>Dernier message: {{ message.modifyAt|date('d/m/Y à H:i') }}</small>
                        </a>
                        <div>
                            <button class="favorite-toggle" aria-label="Basculer le favori">
                                {{ app.user.favorite.contains(message) ? '❤️' : '🤍' }}
                            </button>
                            <button
                                    class="delete-button"
                                    data-id="{{ message.id }}"
                                    data-csrf="{{ csrf_token('delete' ~ message.id) }}"
                                    aria-label="Supprimer le message">🗑️
                            </button>
                        </div>
                    </li>
                {% else %}
                    <li aria-live="polite">Aucune conversation.</li>
                {% endfor %}
            </ul>
        </section>
        <div class="pagination" aria-label="Pagination des messages">
            {{ knp_pagination_render(messages) }}
        </div>

    </main>

{% endblock %}

app/templates/message/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}Message !{% endblock %}
{% block javascripts %}
    <script src="{{ asset('js/message_view.js') }}" defer></script>
{% endblock %}

{% block body %}
    <main id="message_view" aria-label="Vue détaillée du message">
        <section id="hero_message_view" aria-labelledby="message_subject">
            <h1 id="message_subject">Sujet : {{ message.subject ?: '(sans sujet)' }}</h1>
            <p><strong>De :</strong> {{ message.sender.name ?: message.sender.email }}</p>
            <p><strong>À :</strong> {{ message.recipient.name ?: message.recipient.email }}</p>
            <p><strong>Premier envoi :</strong> {{ message.createdAt|date('d/m/Y à H:i') }}</p>
        </section>

        <section id="content_message_view" aria-label="Contenu de la discussion">
            <h2 class="hidden">Discussion :</h2>
            <div>{{ message.content|raw |nl2br }}
                <div>
                    <p>Pièce(s) jointe(s) :</p>
                    <ul>
                        {% for file in message.files %}
                            <li>
                                <a href="{{ path('secure_file', { id: file.id }) }}" aria-label="Télécharger {{ file.originalName ?: file.name }}">
                                    {{ file.originalName ?: file.name }}
                                </a>
                            </li>
                        {% else %}
                            <li>Aucune pièce jointe.</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            {{ form_start(form, {
                attr: {
                    class: app.user.name == message.sender.name
                    ? 'sender'
                    : (app.user.name == message.recipient.name ? 'recipient' : '')
                }
            }) }}

            <div class="file-upload">
                {{ form_row(form.files, {
                    attr: {
                        class: 'input-fichier-cache',
                        'aria-label': 'Ajouter un fichier en pièce jointe'
                    },
                    label: false
                }) }}

                <label for="answer_form_files" class="label-piece-jointe" title="Ajouter un fichier" aria-label="Ajouter un fichier en pièce jointe">
                    🖇️
                </label>
            </div>
            <div>
                <div>
                    {{ form_row(form.reponse) }}
                    <button type="submit" aria-label="Envoyer la réponse">▶</button>
                </div>
                <div id="file-names" class="file-names" aria-live="polite" aria-atomic="true"></div>
            </div>

            {{ form_end(form) }}
        </section>
    </main>
{% endblock %}